CREATE TABLE users(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username TEXT,
  bio TEXT,
  clerk_id TEXT,
  date_joined DATE NOT NULL DEFAULT CURRENT_DATE );
CREATE TABLE posts(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  title TEXT,
  content TEXT,
  clerk_id TEXT,
  post_date DATE NOT NULL DEFAULT CURRENT_DATE,
  likes INT NOT NULL DEFAULT 0,
  image TEXT );

CREATE TABLE comments(
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    content TEXT,
    clerk_id TEXT,
    post_id INT,
    likes INT NOT NULL DEFAULT 0,
    comment_date DATE NOT NULL DEFAULT CURRENT_DATE );